#!/usr/bin/env tclsh

set task [lindex $argv 0]
set toifile [pwd]/toi.tcl
set toibasedir [file dirname [info script]]

source $toibasedir/cli.tcl

# safety checks:
validate

# include the standard 'toi' commands:
source $toibasedir/commands.tcl
# include the user's toi file:
source $toifile

# Does the called task exist?
task_exists? $task

# execute the called task:
puts [$task]




# vim: set filetype=tcl
